apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      env: myapp
  template:
    metadata:
      labels:
        env: myapp
    spec:
      containers:
      - name: myapp-container
        image: 019071237567.dkr.ecr.us-east-2.amazonaws.com/kumar-ecr:latest
        ports:
        - containerPort: 8080
